/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SupplierRole;

import enterprise.Enterprise;
import javax.swing.table.DefaultTableModel;
import business.models.Product.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tinyteddybear
 */

public class ProductDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductDirectoryJPanel
     */
    private int pFlag;
    private Enterprise enterprise;
    private JPanel rightPanel;
    public ProductDirectoryJPanel(Enterprise enterprise,JPanel rightPanel) {
        initComponents();
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productDirTbl = new javax.swing.JTable();
        productComboBox = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();

        productDirTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(productDirTbl);

        productComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seed", "Tumbler", "Crop", "Compost" }));
        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Item");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(deleteBtn)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(deleteBtn)))
                .addContainerGap(447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
    String value = productComboBox.getSelectedItem().toString();
    
        switch (value) {
            case "Crop":
                pFlag = 1;
                populatetable(pFlag);
                break;
            case "Tumbler":
                pFlag = 2;
                populatetable(pFlag);
                break;
            case "Seed":
                pFlag = 3;
                populatetable(pFlag);
            case "Compost":
                pFlag=4;
                 populatetable(pFlag);
            }
   
    
        
        
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = productDirTbl.getSelectedRow();

       if(selectedRow >= 0){
           int decision = JOptionPane.showConfirmDialog(rightPanel, "Do you really want to remove this Item from Product directory?", "Warning", JOptionPane.YES_NO_OPTION);
           if(decision == JOptionPane.YES_OPTION){
               Product product = (Product) productDirTbl.getValueAt(selectedRow, 0);
               enterprise.getProductDirectory().removeItem(product);
               JOptionPane.showMessageDialog(rightPanel, "Product deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
               populatetable(pFlag);
           }
       } else
           JOptionPane.showMessageDialog(rightPanel, "Please select a row.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_deleteBtnActionPerformed

    

public void populatetable(int n)
{
    DefaultTableModel model = (DefaultTableModel)productDirTbl.getModel();
        
        model.setRowCount(0);
        
        enterprise.getProductDirectory().getProducts().stream().forEach((p) -> {
            Object[] row = new Object[6];
            
            if (n==1)
            {
                if (p instanceof CropProduce)
                {
                    row[0] = p;
                    row[1] = p.getName();
                    row[2] = ((CropProduce) p).getProductId();
                    row[3] = ((CropProduce) p).getPrice();
                    row[4] = ((CropProduce) p).getCropQuantity();
                    model.addRow(row);
                }
            }
            else if (n==2)
            {
                if (p instanceof Tumbler)
                {
                    row[0] = p;
                    row[1] = p.getName();
                    row[2] = ((Tumbler) p).getProductId();
                    row[3] = ((Tumbler) p).getPrice();
                    row[4] = ((Tumbler) p).getCapacity();
                    model.addRow(row);
                }
            }
            else if ( n==4)
            {
                  if (p instanceof Compost)
                {
                    row[0] = p;
                    row[1] = p.getName();
                    row[2] = ((Compost) p).getProductId();
                    //row[3] = ((Tumbler) p).getPrice();
                    row[4] = ((Compost) p).getQuantity();
                    


                    model.addRow(row);
                }
            

            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JTable productDirTbl;
    // End of variables declaration//GEN-END:variables
}
