/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Ecosystem;
import business.models.User.User;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aditya
 */
public class LoginJPanel extends javax.swing.JPanel {
    private final JPanel rightPanel;
    private final Ecosystem system;
    

    LoginJPanel(JPanel rightPanel, Ecosystem system) {
        initComponents();
        this.rightPanel = rightPanel;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIdLabel = new javax.swing.JLabel();
        userIdTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        forgotPswrdBttn = new javax.swing.JButton();
        loginBttn = new javax.swing.JButton();
        regBttn = new javax.swing.JButton();
        loginScreenLabel = new javax.swing.JLabel();
        backBttn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(1022, 650));

        userIdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userIdLabel.setText("User ID:");

        userIdTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdTextFieldActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel.setText("Password:");

        forgotPswrdBttn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forgotPswrdBttn.setText("Forgot Password?");
        forgotPswrdBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPswrdBttnActionPerformed(evt);
            }
        });

        loginBttn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginBttn.setText("Login ");
        loginBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBttnActionPerformed(evt);
            }
        });

        regBttn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regBttn.setText("Register");
        regBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBttnActionPerformed(evt);
            }
        });

        loginScreenLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginScreenLabel.setText("LOGIN");

        backBttn.setText("Back");
        backBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(375, 375, 375)
                            .addComponent(passwordLabel)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(regBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(forgotPswrdBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(386, 386, 386)
                            .addComponent(userIdLabel)
                            .addGap(18, 18, 18)
                            .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBttn)
                            .addComponent(loginScreenLabel))))
                .addGap(422, 422, 422))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginScreenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBttn)
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdLabel)
                    .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgotPswrdBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regBttn)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdTextFieldActionPerformed

    private void forgotPswrdBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPswrdBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPswrdBttnActionPerformed

    private void loginBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBttnActionPerformed
        // TODO add your handling code here:
        String userName = userIdTextField.getText();
         char[] input = passwordField.getPassword();
         String password = String.valueOf(input);
         
         User userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
         
//        if(userIdTextField.getText().equals("sysadmin") && password.equals("sysadmin")){
//            SystemAdminWorkAreaJPanel sysAdminScreen = new SystemAdminWorkAreaJPanel(rightPanel, null);
//            rightPanel.add("SystemAdminWorkAreaJPanel", sysAdminScreen);
//            CardLayout layout = (CardLayout) rightPanel.getLayout();
//            layout.next(rightPanel);
//        }        
         
         if(userAccount != null){
            CardLayout layout=(CardLayout)rightPanel.getLayout();
            rightPanel.add("workArea",userAccount.getRole().createWorkArea(rightPanel, userAccount, null, null, system));
            layout.next(rightPanel);
         }
         
    }//GEN-LAST:event_loginBttnActionPerformed

    private void regBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBttnActionPerformed
        // TODO add your handling code here:
        // SignInJPanel createSignInPanel = new SignInJPanel(rightPanel, system);
        // rightPanel.add("createSignInPanel", createSignInPanel);
        // CardLayout layout = (CardLayout) rightPanel.getLayout();
        // layout.next(rightPanel);
    }//GEN-LAST:event_regBttnActionPerformed

    private void backBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttnActionPerformed
        // TODO add your handling code here:
         rightPanel.remove(this);
        CardLayout cardLayout = (CardLayout) rightPanel.getLayout();
        cardLayout.previous(rightPanel);
    }//GEN-LAST:event_backBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBttn;
    private javax.swing.JButton forgotPswrdBttn;
    private javax.swing.JButton loginBttn;
    private javax.swing.JLabel loginScreenLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton regBttn;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField userIdTextField;
    // End of variables declaration//GEN-END:variables
}
